### ISSUE TITLE
Tests fail on Apple Mac when building the project from command line

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gtfs-realtime-validator#102]
**Issue by [lionel-nj](https://github.com/lionel-nj)**
_Jan 19, 2022_
_Originally opened as https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/405_

----

**Summary:** 

Test sets fail when building the project from command line - which prevents the project from building.

**Steps to reproduce:** 

After applying the fix suggested in https://github.com/MobilityData/gtfs-realtime-validator/issues/101, run `mvn package` at the root of the project.

**Expected behavior:** 

Tests pass and project builds. An executable jar should be generated in `target`.

**Observed behavior:** 

Failure in tests that prevent the project from building [(see test reports.zip)](https://github.com/CUTR-at-USF/gtfs-realtime-validator/files/7899456/test.reports.zip)

- `edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest`
- `edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest`
![Screen Shot 2022-02-22 at 3 58 41 PM](https://user-images.githubusercontent.com/63653518/155218214-6b261d3b-d8dd-408d-8e5f-628064b08b27.png)

Interestingly, those test sets are successfully executed in IntelliJ.

"This might have something to do with the HSQLDB drivers on Mac, because those tests test queries against a HSQLDB instance using the JDBC drivers."

"I guess maybe IntelliJ is including something on the classpath that you're missing on command-line? Maybe the JDBC drivers?"

(from @barbeau).

**Platform:** 

Mac M1
MacOS Big Sur 11.6 version
Java 11.0.11

**Comment by isabelle-dr** [comment]
**Comment by [barbeau](https://github.com/barbeau)**
_Jan 19, 2022_

----
Looks like these are related to Hibernate and database access for the web app during the test:
```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
testGtfsFeed(edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest)  Time elapsed: 0.01 s  <<< ERROR!
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
Caused by: java.lang.reflect.InvocationTargetException
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7d934771
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
```

```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.568 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
testViewErrorLogModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.529 s  <<< ERROR!
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: java.lang.reflect.InvocationTargetException
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7d934771
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)

testViewErrorSummaryModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.027 s  <<< ERROR!
org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: java.lang.reflect.InvocationTargetException
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7d934771
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
```

**Comment by barbeau** [comment]
Does anyone else have an M1 Mac to test this issue?

There is a chance it may be resolved by https://github.com/MobilityData/gtfs-realtime-validator/pull/106 when that's merged.

**Comment by isabelle-dr** [comment]
Just tried to build the project from the command line in the #106 branch on my Mac M1, I still get the issue. Here is the [surfire-reports.zip](https://github.com/MobilityData/gtfs-realtime-validator/files/8187288/surfire-reports.zip).

<img width="1290" alt="Screen Shot 2022-03-04 at 11 21 54 AM" src="https://user-images.githubusercontent.com/63653518/156800349-97cb24da-50ec-4fcf-85c0-7c72b9362be0.png">

This also fails from the IntelliJ terminal.

**Comment by barbeau** [comment]
@isabelle-dr What JDK version are you using to build?

**Comment by isabelle-dr** [comment]
@barbeau 16.0.1. Should I update to 17 and see if this works?

**Comment by barbeau** [comment]
Yes, please try 17 and see if you get the same.

**Comment by isabelle-dr** [comment]
Same result with JDK 17: test failures 😭

**Comment by barbeau** [comment]
Interesting - looks like you're getting different errors than Lionel:

```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
testGtfsFeed(edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
```

```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.183 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
testViewErrorLogModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.155 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)

testViewErrorSummaryModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)

```

**Comment by barbeau** [comment]
@isabelle-dr Could you try one more time, this time with JDK 17 running `mvn clean package` to make sure the previous build is deleted first?

**Comment by isabelle-dr** [comment]
The issue persists.

**Comment by barbeau** [comment]
What stack trace are you seeing now? The one you previously saw in https://github.com/MobilityData/gtfs-realtime-validator/issues/102#issuecomment-1061228907, or the one Lionel saw in https://github.com/MobilityData/gtfs-realtime-validator/issues/102#issuecomment-1048207734?

**Comment by isabelle-dr** [comment]
Here is exactly what I did:
1. `mvn clean package` -> I got the error in the terminal, didn't open the surefire reports.
2. `mvn clean` -> this is the output
<img width="375" alt="Screen Shot 2022-03-10 at 7 07 03 PM" src="https://user-images.githubusercontent.com/63653518/157776266-f5e88c6b-fc30-41f0-b91b-d0b169240ae1.png">
3. `mvn package`
<img width="1226" alt="Screen Shot 2022-03-10 at 7 10 22 PM" src="https://user-images.githubusercontent.com/63653518/157776616-89033ce3-1a21-4c62-bb65-0b6e541a2932.png">

Here is the [surefire-reports.zip](https://github.com/MobilityData/gtfs-realtime-validator/files/8227939/Archive.zip).
There are more files in it than last time...

This being said, the `gtfs-realtime-validator-lib-1.0.0-SNAPSHOT.jar` is created and it works perfectly. 
Here is the content of the "target" directory that was created when I ran `mvn package`. I then added the files `TripUpdates.pb`, `gtfs.zip` to run the validator on the JAR file and I got the results in `TripUpdates.pb.results.json`

<img width="732" alt="Screen Shot 2022-03-10 at 7 21 01 PM" src="https://user-images.githubusercontent.com/63653518/157777646-e5444c9a-f3c8-45a1-aca7-2d62554f9568.png">

**Comment by barbeau** [comment]
Can you share the surefire-reports for the webapp project?

The one you linked only has the test results for the `lib` project.

From the above screenshot this should be in `/users/isabelle/Documents/GitHub/gtfs-realtime-validator/gtfs-realtime-validator-webapp/target/surefire-reports`.  

We're specifically looking for the test results for `GtfsFeedTest` and `QueryTest`.

The reason why this is important is that right now we have two different sets of stack traces potentially related to this issue, and if we can narrow it back down to one (i.e., if your current output matches what Lionel originally saw) it will make it easier to fix the issue. The stack trace you previously saw should have been fixed in #106.

**Comment by isabelle-dr** [comment]
Oh right - sorry about that 😅.
Sure, here are the surefire-reports for the webapp: [surefire-reports_webapp.zip](https://github.com/MobilityData/gtfs-realtime-validator/files/8235807/surefire-reports_webapp.zip). They are the same than seen previously (different ones than Lionel's).
```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest
testGtfsFeed(edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeedTest.setUp(GtfsFeedTest.java:44)
```

```
-------------------------------------------------------------------------------
Test set: edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.203 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest
testViewErrorLogModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.183 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)

testViewErrorSummaryModel(edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at edu.usf.cutr.gtfsrtvalidator.test.queries.QueryTest.setUp(QueryTest.java:65)
```
